[package]
name = "starfish-paint"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
starfish-dom = { workspace = true }
starfish-html = { workspace = true }
starfish-css = { workspace = true }
starfish-style = { workspace = true }
starfish-layout = { workspace = true }
starfish-net = { workspace = true }
starfish-js = { workspace = true }

tiny-skia = "0.11"
fontdue = "0.9"
fontdb = "0.23"

[dependencies.image]
version = "0.25"
default-features = false
features = ["png", "jpeg"]

[dev-dependencies]
tiny_http = "0.12"
base64 = "0.22.1"
