[package]
name = "starfish-layout"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
starfish-dom = { workspace = true }
starfish-style = { workspace = true }
unicode-bidi = "0.3.18"

[dev-dependencies]
starfish-html = { workspace = true }
starfish-css = { workspace = true }
